os: windows
matrix:
    include:        
        - language: cpp
          script:
            - mkdir build
            - cd build
            - cmake .. -G "Visual Studio 15 2017"
            - cmake --build . --config Releae