os: windows
matrix:
    include:        
        - language: cpp
          compiler: gcc
          script:
            - mkdir build
            - cd build
            - cmake ..
            - cmake --build . --configure Releae